import { MockupCustomShape, MockupCustomShapeTypes } from "./src/MockupCustomShape";


export const MockupShapes = [
    { name: MockupCustomShapeTypes[0].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[0] },
    { name: MockupCustomShapeTypes[1].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[1] },
    { name: MockupCustomShapeTypes[2].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[2] },
    { name: MockupCustomShapeTypes[3].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[3] },
    { name: MockupCustomShapeTypes[4].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[4] },
    { name: MockupCustomShapeTypes[5].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[5] },
    { name: MockupCustomShapeTypes[6].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[6] },
    { name: MockupCustomShapeTypes[7].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[7] },
    { name: MockupCustomShapeTypes[8].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[8] },
    { name: MockupCustomShapeTypes[9].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[9] },
    { name: MockupCustomShapeTypes[10].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[10] },
    { name: MockupCustomShapeTypes[11].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[11] },
    { name: MockupCustomShapeTypes[12].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[12] },
    { name: MockupCustomShapeTypes[13].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[13] },
    { name: MockupCustomShapeTypes[14].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[14] },
    { name: MockupCustomShapeTypes[15].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[15] },
    { name: MockupCustomShapeTypes[16].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[16] },
    { name: MockupCustomShapeTypes[17].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[17] },
    { name: MockupCustomShapeTypes[18].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[18] },
    { name: MockupCustomShapeTypes[19].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[19] },
    { name: MockupCustomShapeTypes[20].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[20] },
    { name: MockupCustomShapeTypes[21].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[21] },
    { name: MockupCustomShapeTypes[22].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[22] },
    { name: MockupCustomShapeTypes[23].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[23] },
    { name: MockupCustomShapeTypes[24].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[24] },
    { name: MockupCustomShapeTypes[25].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[25] },
    { name: MockupCustomShapeTypes[26].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[26] },
    { name: MockupCustomShapeTypes[27].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[27] },
    { name: MockupCustomShapeTypes[28].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[28] },
    { name: MockupCustomShapeTypes[29].name, type: MockupCustomShape, typeInfo: MockupCustomShapeTypes[29] },
]