import { CustomEntityTypeInfo } from "../../Items/src/CustomEntity";
import { FlowChartShape, FlowChartShapeTypes } from "./src/FlowChartShape";

export const FlowChartShapes: CustomEntityTypeInfo[] = [
    { name: FlowChartShapeTypes[0].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[0] },
    { name: FlowChartShapeTypes[1].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[1] },
    { name: FlowChartShapeTypes[2].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[2] },
    { name: FlowChartShapeTypes[3].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[3] },
    { name: FlowChartShapeTypes[4].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[4] },
    { name: FlowChartShapeTypes[5].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[5] },
    { name: FlowChartShapeTypes[6].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[6] },
    { name: FlowChartShapeTypes[7].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[7] },
    { name: FlowChartShapeTypes[8].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[8] },
    { name: FlowChartShapeTypes[9].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[9] },
    { name: FlowChartShapeTypes[10].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[10] },
    { name: FlowChartShapeTypes[11].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[11] },
    { name: FlowChartShapeTypes[12].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[12] },
    { name: FlowChartShapeTypes[13].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[13] },
    { name: FlowChartShapeTypes[14].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[14] },
    { name: FlowChartShapeTypes[15].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[15] },
    { name: FlowChartShapeTypes[16].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[16] },
    { name: FlowChartShapeTypes[17].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[17] },
    { name: FlowChartShapeTypes[18].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[18] },
    { name: FlowChartShapeTypes[19].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[19] },
    { name: FlowChartShapeTypes[20].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[20] },
    { name: FlowChartShapeTypes[21].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[21] },
    { name: FlowChartShapeTypes[22].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[22] },
    { name: FlowChartShapeTypes[23].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[23] },
    { name: FlowChartShapeTypes[24].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[24] },
    { name: FlowChartShapeTypes[25].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[25] },
    { name: FlowChartShapeTypes[26].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[26] },
    { name: FlowChartShapeTypes[27].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[27] },
    { name: FlowChartShapeTypes[28].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[28] },
    { name: FlowChartShapeTypes[29].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[29] },
    { name: FlowChartShapeTypes[30].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[30] },
    { name: FlowChartShapeTypes[31].name, type: FlowChartShape, typeInfo: FlowChartShapeTypes[31] },
]